/**
 * Extension for Express Session
 * Generated by ts-error-fixer-batch.js
 */

declare module 'express-session' {
  interface SessionData {
    user: any;
    userId: string;
    isAuthenticated: boolean;
    csrf: string;
    returnTo: string;
    viewCount: number;
    lastVisit: Date;
    // Add other session properties here as needed
  }
}
